apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "overops-collector.fullname" . }}
  labels:
    {{- include "overops-collector.labels" . | nindent 4 }}
data:
  {{- if .Values.overops.serviceKey  }}
  installation.key:  {{ .Values.overops.serviceKey }}
  {{- end }}
  collector.properties: |-
     jvmPath=${JAVA_HOME}/lib/amd64/server/libjvm.so
     libraryPath=/opt/takipi/lib

     takipi.listen.port=6060
     {{- if .Values.overops.backendURL }}
     takipi.backend.url={{ .Values.overops.backendURL }}
     {{- else }}
     takipi.backend.url={{ include "overops-collector.hostedBackendURL" . }}
     {{- end }}
     {{- if .Values.overops.storageTestURL }}
     takipi.storage.test.url={{ .Values.overops.storageTestURL }}
     {{- else }}     
     takipi.storage.test.url={{ include "overops-collector.hostedBackendURL" . }}/service/png
     {{- end }}
     {{- if .Values.overops.serverName }}
     takipi.server.name={{ .Values.overops.serverName }}
     {{- end }}
