# Default values for overops-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  repository: overops/server
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

# Database Section
## Default use of mysql 
database:
  type: "mysql"

mysql:
  enabled: true

  mysqlUser: "overops"
  mysqlPassword: 
  mysqlRootPassword:
  service:
    port: 3306
  initializationFiles:
    initdb.sql: |-
      use sys;

      GRANT ALL PRIVILEGES ON * . * TO 'overops'@'%';
      FLUSH PRIVILEGES;

      CREATE DATABASE IF NOT EXISTS dynalite;
      CREATE DATABASE IF NOT EXISTS pds;
      CREATE DATABASE IF NOT EXISTS qsql;
      CREATE DATABASE IF NOT EXISTS takipi;

# Networking
frontendURL: "http://overops.127.0.0.1.nip.io:8080/"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: overops.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

ambassador:
  enabled: false
  prefix: /

resources: {}
#  requests:
#    cpu: "500m"
#    memory: "4Gi"

## Persist data to a persistent volume
persistence:
  enabled: true
  ## database data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  accessMode: ReadWriteOnce
  size: 20Gi
  annotations: {}

autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}


## Config:
configurationFiles:
  my.server.properties: |-
    GRAFANA_DASHBOARD_ENABLED: true
    LOCAL_DEFAULT_USER_JSON: 
    LOCAL_DEFAULT_USER_SERVICE_SECRET_KEY: 


serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
